services:
  spaceship_ddns:
    container_name: spaceship_ddns
    build: .
    env_file: .env
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
